In [81]:
# Import the numpy library and create the "grades" array as specified 
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [3]:
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [49]:
# Calculate mean
grades_mean = np.mean(grades)
grades_mean

87.5

In [53]:
# median
grades_median = np.median(grades)
grades_median

88.5

In [55]:
# standard deviation
grades_std = np.std(grades)
grades_std

6.591661399070799

In [67]:
grades_max = np.max(grades)
grades_max

98

In [65]:
grades_min = np.min(grades)
grades_min

75

In [69]:
# Use numpy function to sort the grades in ascending order.
sorted_grades = np.sort(grades)
sorted_grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [75]:
# Use numpy function to find the index of the highest grade in the array
index_highest_grade = np.argmax(grades)
index_highest_grade

7

In [37]:
# Use numpy function to count the number of students who scored above 90.
students_above_90 = np.sum(grades > 90)
students_above_90

3

In [79]:
# Calculate the percentage of students who scored above 90
percentage_above_90 = (students_above_90 / len(grades)) * 100
percentage_above_90

30.0

In [43]:
# Calculate the percentage of students who scored below 75
students_below_75 = np.sum(grades < 75)
percentage_below_75 = (students_below_75 / len(grades)) * 100
percentage_below_75

0.0

In [45]:
# Extract all grades above 90 into "high_performers"
high_performers = grades[grades > 90]
high_performers

array([92, 95, 98])

In [47]:
# Create a new array "passing_grades" with grades above 75
passing_grades = grades[grades > 75]
passing_grades 

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [77]:
# Printing all the results
print(f"Grades: {grades}")
print(f"Mean: {grades_mean}")
print(f"Median: {grades_median}")
print(f"Standard Deviation: {grades_std}")
print(f"Maximum Grade: {grades_max}")
print(f"Minimum Grade: {grades_min}")
print(f"Sorted Grades: {sorted_grades}")
print(f"Index of Highest Grade: {index_highest_grade}")
print(f"Number of Students Above 90: {students_above_90}")
print(f"Percentage of Students Above 90: {percentage_above_90:.2f}%")
print(f"Percentage of Students Below 75: {percentage_below_75:.2f}%")
print(f"High Performers: {high_performers}")
print(f"Passing Grades: {passing_grades}")


Grades: [85 90 88 92 95 80 75 98 89 83]
Mean: 87.5
Median: 88.5
Standard Deviation: 6.591661399070799
Maximum Grade: 98
Minimum Grade: 75
Sorted Grades: [75 80 83 85 88 89 90 92 95 98]
Index of Highest Grade: 7
Number of Students Above 90: 3
Percentage of Students Above 90: 30.00%
Percentage of Students Below 75: 0.00%
High Performers: [92 95 98]
Passing Grades: [85 90 88 92 95 80 98 89 83]
